name: license

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , snapshot , master ]
  pull_request:
    branches: [ main , snapshot , master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017 # v4.0.0
      - name: Check License Header
        uses: apache/skywalking-eyes@6b2529214f6b1ccee3ec92bb0adfeabf6f66f538 # v0.5.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # needed only when you want License-Eye to comment on the pull request.https://github.com/eclipse/org.eclipse.sensinact.gateway/tree/future/prototype/prototype
